### ISSUE TITLE
比赛活动 & 负责人征集

### ISSUE THREAD

**Issue by wizardforcel** [apachecn/Interview#260]
> 如果你有想法，有热情参与某个比赛（或者复现某个现有比赛），但苦于没人一起组队的话，加入我们，成为比赛活动负责人吧！发起你的活动，招募队友，互相学习，争取更大的胜利！

请在这个 ISSUE 中留言，“昵称 + QQ + 比赛名称”，**示例**：“飞龙+562826179+kaggle Leaf Classification”。

| 负责人 | QQ | 比赛名称 | 备注 |
| --- | --- | --- | --- |
| 张一极 | 2533524298 | 手写数字百分百准确率模型探究 |
| 呆呆 | 728634974 |  | ds、kdd相关皆可，个人水平kaggle top20，cv的话小数据集可以，我这里算力有限 |
| Roman | 570515024 |  | 大数据 |
| 1266 | 1097828409 | [桑坦德客户交易预测](https://www.kaggle.com/c/santander-customer-transaction-prediction) |
| Datawhale | - | [搭建文本情感分类模型](https://mp.weixin.qq.com/s/iM7pm0HxuTVgVvLClngN_A) |

---

比赛平台

* https://www.kaggle.com
* https://tianchi.aliyun.com
* https://www.tinymind.cn
* https://www.flyai.com

**Comment by AllenZYJ** [comment]
张一极 + 2533524298 + 手写数字百分百准确率模型探究

**Comment by daidai21** [comment]
呆呆+728634974+（ds、kdd相关皆可，个人水平kaggle top20，cv的话小数据集可以，我这里算力有限）

**Comment by bihu-romantic** [comment]
Roman+570515024+（大数据）

**Comment by wangweitong** [comment]
1266-1097828409-(桑坦德客户交易预测)https://www.kaggle.com/c/santander-customer-transaction-prediction

**Comment by jiangzhonglian** [comment]
1. 如何在 Python 中使用 XGBoost 调整决策树的数量和大小
https://github.com/apachecn/ml-mastery-zh/blob/master/docs/xgboost/tune-number-size-decision-trees-xgboost-python.md

**Comment by yingenglei** [comment]
雷+402930483+（ds、kdd相关皆可，个人水平kaggle top20，cv的话小数据集可以，我这里算力有限）
