### ISSUE TITLE
【收集】特征工程

### ISSUE THREAD

**Issue by jiangzhonglian** [apachecn/Interview#274]
up主你好，有机会可以讲解一下特征选择过程吗？有关于特征选择过程中特征抽取算法的，比如启发式算法的过程

已经合并更新到： https://github.com/apachecn/Interview/issues/343

**Comment by jiangzhonglian** [comment]
使用sklearn做单机特征工程
https://www.cnblogs.com/jasonfreak/p/5448385.html



特征工程系列：特征筛选的原理与实现（上）
https://www.cnblogs.com/purple5252/p/11205500.html

特征工程系列：特征筛选的原理与实现（下）
https://www.cnblogs.com/purple5252/p/11211083.html

**Comment by xixici** [comment]
怎么这么好的干货放在了这里 

> 使用sklearn做单机特征工程
> https://www.cnblogs.com/jasonfreak/p/5448385.html
> 
> 特征工程系列：特征筛选的原理与实现（上）
> https://www.cnblogs.com/purple5252/p/11205500.html
> 
> 特征工程系列：特征筛选的原理与实现（下）
> https://www.cnblogs.com/purple5252/p/11211083.html

**Comment by jiangzhonglian** [comment]
这个还是在收集阶段，哈哈哈
