### ISSUE TITLE
系统设计补完计划

### ISSUE THREAD

**Issue by wizardforcel** [apachecn/Interview#306]
在 Interview 项目中添加系统设计面试解答

（1）我之前翻译过一个小册子，可以合并进来：

https://github.com/apachecn/gainlo-interview-guide-zh

（2）一亩三分地有个系统设计版，很多人在里面贴英文的资源，可以翻译

https://www.1point3acres.com/bbs/forum-323-1.html

（3）HighScalability.com 是个权威的站点，但是我不知道从哪里下手。

---

转到新的连接:  https://github.com/apachecn/Interview/issues/273

**Comment by jiangzhonglian** [comment]
1. 如何写好一份简历
2. 如何去投递简历
3. 如何刷题
4. 如何刷项目
5. 面试心得

**Comment by xixici** [comment]
> 1. 如何写好一份简历
> 2. 如何去投递简历
> 3. 如何刷题
> 4. 如何刷项目
> 5. 面试心得

      需要我将 @wizardforcel  的册子合进来吗？ 这个我可以做了 @jiangzhonglian
