### ISSUE TITLE
原来的kaggle入门讲解与一些项目的内容怎么没了

### ISSUE THREAD

**Issue by jsrdcht** [apachecn/Interview#339]

**Comment by jiangzhonglian** [comment]
Kaggle 官方系列

[【Kaggle官方系列: 入门教程 + 竞赛项目】](https://github.com/apachecn/Interview/tree/master/docs/Kaggle)


![image](https://user-images.githubusercontent.com/9199175/88679811-6a419e80-d122-11ea-838e-42a7740ac5c3.png)
