### ISSUE TITLE
算法刷题，推荐《LeetCode Cookbook》

### ISSUE THREAD

**Issue by halfrost** [apachecn/Interview#346]
去年刷了一年的题，把每道题的题解都整理在这里了：https://github.com/halfrost/LeetCode-Go/
解题汇集成了这本《LeetCode Cookbook》。

> 作者如果觉得质量还可以，可以把我这里链接放在算法刷题的专栏下面。

**Comment by jiangzhonglian** [comment]
好的呢，这个很棒！

**Comment by jiangzhonglian** [comment]
已经添加了， 关闭此 issues
