### ISSUE TITLE
国内gitee网站404了，突出一个抽象，真的摇摇领先了

### ISSUE THREAD

**Issue by scorpion9111** [apachecn/Interview#355]
https://apachecn.gitee.io/interview国内gitee网站404了，突出一个抽象，真的摇摇领先了

**Comment by kangyuqi** [comment]
已收到您的邮件，谢谢。

**Comment by jiangzhonglian** [comment]
> [https://apachecn.gitee.io/interview国内gitee网站404了，突出一个抽象，真的摇摇领先了](https://apachecn.gitee.io/interview%E5%9B%BD%E5%86%85gitee%E7%BD%91%E7%AB%99404%E4%BA%86%EF%BC%8C%E7%AA%81%E5%87%BA%E4%B8%80%E4%B8%AA%E6%8A%BD%E8%B1%A1%EF%BC%8C%E7%9C%9F%E7%9A%84%E6%91%87%E6%91%87%E9%A2%86%E5%85%88%E4%BA%86)

好兄弟，你看看这个地址： <https://interview.apachecn.org>   (gitee 不维护了)
